const mongoose = require('mongoose');

//Here we define the User Model


const machineSchema = new mongoose.Schema({

    name:{
        type:String
    },
    type:{
        type:String
    },
    categories:[],
    userID:{
        type:String
    },
    serialNumber:{
        type:String
    },
    standard:{
        type:String
    },
    fixedFiles:{
        safetyList:{
            links:[]
        },
        safetyMatrix:{
            links:[]
        },
        riskAssessmentStudy:{
            links:[]
        },
        calculationsFile:{
            links:[]
        },
        testsFile:{
            links:[]
        },
        regulationsFile:{
            links:[]
        },
        manuals:{
            links:[]
        },
        qualityControl:{
            links:[]
        }
    },
    manualFiles:{
        designs:{
            links:[]
        },
        partsDeclarationsOfCompliance:{
            links:[]
        },
        photos:{
            links:[]
        }
      
    },
    variableFiles:[
        {
            qualityControlAndTests:{
                data:{

                    issueDate:{
                        type:Date
                    },
                    productionDate:{
                        type:Date
                    },
                    productionManager:{
                        type:String
                    }
                },
                fileCode:{
                    type:String
                }
            },
            production:{
                data:{
                    orderNumber:{
                        type:String
                    },
                    quantity:{
                        type:Number
                    },
                    jobs:{
                        cuts:{
                            name:{
                                type:String
                            },
                            date:{
                                type:Date
                            }
                        },
                        soldering:{
                            name:{
                                type:String
                            },
                            date:{
                                type:Date
                            }
                        },
                        modding:{
                            name:{
                                type:String
                            },
                            date:{
                                type:Date
                            }
                        }
                    },

                    startDate:{
                        type:Date
                    },
                
                    productionManager:{
                        type:String
                    }
                },
                fileCode:{
                    type:String
                }
            },
            partsList:{
                data:{

                    issueDate:{
                        type:Date
                    },
                    productionDate:{
                        type:Date
                    },
                    productionManager:{
                        type:String
                    },
                    parts:[{
                        name:{
                            type:String
                        },
                        description:{
                            type:String
                        },
                        serialNumber:{
                            type:String
                        },
                        vendor:{
                            type:String
                        }
                    }]
                },
                fileCode:{
                    type:String
                }
            },
            declarationOfCompliance:{
                data:{

                    issueDate:{
                        type:Date
                    },
                    productionDate:{
                        type:Date
                    },
                    productionManager:{
                        type:String
                    }
                },
                fileCode:{
                    type:String
                }
            },
            serialNumber:{
                type:String
            }
        }
    ]
  
});


module.exports = mongoose.model("Machine",machineSchema, "Machines");